CREATE TABLE Games(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL UNIQUE,
	ReleaseDate DATETIME NOT NULL,
	TotalRating FLOAT(10) NOT NULL,
	GameDetails NVARCHAR(200) NOT NULL,
	ImageSrc NVARCHAR(200) NOT NULL
);

CREATE TABLE Genres(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL UNIQUE,
);

CREATE TABLE Platforms(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE Developers(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL UNIQUE,
	Headquarters NVARCHAR(30) NOT NULL
);

CREATE TABLE GameGenre(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GameId INT NOT NULL FOREIGN KEY REFERENCES Games(ID),
	GenreId INT NOT NULL FOREIGN KEY REFERENCES Genres(ID),
);

CREATE TABLE GamePlatform(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GameId INT NOT NULL FOREIGN KEY REFERENCES Games(ID),
	PlatformId INT NOT NULL FOREIGN KEY REFERENCES Platforms(ID),
);

CREATE TABLE GameDeveloper(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GameId INT NOT NULL FOREIGN KEY REFERENCES Games(ID),
	DeveloperId INT NOT NULL FOREIGN KEY REFERENCES Developers(ID)
);

CREATE TABLE Users(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Username NVARCHAR(30) NOT NULL UNIQUE,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
);

CREATE TABLE Reviews(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GameId INT NOT NULL FOREIGN KEY REFERENCES Games(ID),
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Rating FLOAT(10) NOT NULL CHECK (Rating >= 1 AND Rating <=10),
	Content NVARCHAR(200) NOT NULL
);

CREATE TABLE Comments(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GameId INT NOT NULL FOREIGN KEY REFERENCES Games(ID),
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	Content NVARCHAR(200) NOT NULL
);

CREATE TABLE Replies(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
	CommentId INT NOT NULL FOREIGN KEY REFERENCES Comments(ID),
	Content NVARCHAR(200) NOT NULL
);